version: '3.8'

services:
  app:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450